package com.devtoolbox.inspirationalvideoapp.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;

import java.util.Date;

@DynamoDBTable(tableName="inspiration-item")
@Data
public class InspirationItem {

    public InspirationItem(){}

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "type-voteCount-index")
    private Long voteCount;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "type-voteCount-index")
    private String type;
    private String submitterUsername;
    private String submitterEmail;
    private String url;
    private Date createdAt;

}
