package com.devtoolbox.inspirationalvideoapp.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Builder;
import lombok.Data;

import java.util.Date;

@DynamoDBTable(tableName="inspirational-video")
@Data
@Builder
public class Video {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBRangeKey
    private Long voteCount;

    private String submitterUsername;
    private String submitterEmail;
    private String videoUrl;
    private Date createdAt;
}
